export const demoLeadsDetails = [
  {
    id: 0,
    name: "Jane Reyes",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    topic: "Improving cost per cup",
    status: "New",
    created_on: "3/10/2024-09:30 AM",
    title: "COO • Northwind Traders",
    note: "Expand business • High buying content",
    schedule: "Engage with Jane Reyes",
    schedule_note:
      "Jane may be interested in upgrading expresso machines for her in-store coffee shops",
    about:
      "Jane Reyes, the Chief Operating Officer of Northwind Traders, is a dynamic leader with a proven track record in optimizing operations and enhancing customer experiences. Under her guidance, Northwind Traders' in-store coffee shops have flourished, becoming a hallmark of quality and innovation. Jane's commitment to excellence makes an ideal partner for First Coffee. She is always seeking top-tier equipment to elevate her coffee shops' offering, ensuring consistent, high quality service",
    reasons: [
      "Jane is a key decision maker and was browsing expresso machineson First Coffee's website",
      "Multiple people at her company have reported slowness during service requests",
      "Northwind Traders currently see $200M in revenue from their in-store coffee shops",
    ],
  },
  {
    id: 1,
    name: "Allan Munger",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    topic: "Improving cost per cup",
    status: "New",
    created_on: "3/10/2024-09:30 AM",
    title: "Head of Real Estate Development • Contoso Coffee",
    note: "Upcoming meeting • Due today",
    schedule: "Prepare for meeting with Alan",
    schedule_note:
      "Prepare for high-buying intent meeting Copilot scheduled for 2 PM regarding upgrading service contract",
    about:
      "Allan Munger, Head of Real Estate Development at Contoso Coffee, is a seasoned expert in identifying strategic locations for coffee shops. With a keen eye for detail and a deep understanding of the coffee industry, Allan has successfully expanded Contoso Coffee's footprint across the region.",
    reasons: [
      "Allan is leading the expansion of Contoso Coffee's retail presence.",
      "He has identified potential locations for new stores in high-traffic areas.",
      "Allan is responsible for negotiating lease agreements with landlords.",
    ],
  },
  {
    id: 2,
    name: "Eva Moreno",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    topic: "Coffee Machine Maintenance",
    status: "In Progress",
    created_on: "3/12/2024-10:45 AM",
    title: "Facilities Manager • The Coffee Club",
    note: "Follow-up meeting • Next week",
    schedule: "Send follow-up email to Eva",
    schedule_note: "Check if Eva has reviewed the maintenance contract",
    about:
      "Eva Moreno, Facilities Manager at The Coffee Club, is dedicated to ensuring seamless day-to-day operations. With her expertise in maintenance and repairs, Eva keeps The Coffee Club's equipment running smoothly, allowing the team to focus on delivering exceptional customer experiences.",
    reasons: [
      "Eva is responsible for scheduling regular maintenance for all equipment.",
      "She has implemented a quality control process to ensure high standards.",
      "Eva collaborates with store managers to address any facilities-related issues.",
    ],
  },
  {
    id: 3,
    name: "Liam Chen",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
    topic: "New Store Opening",
    status: "New",
    created_on: "3/15/2024-11:15 AM",
    title: "Store Owner • The Daily Grind",
    note: "Initial consultation • Today",
    schedule: "Meet with Liam to discuss store opening",
    schedule_note: "Discuss equipment and supply needs for new store",
    about:
      "Liam Chen, Store Owner of The Daily Grind, is passionate about serving high-quality coffee to his community. With a keen interest in innovative brewing methods, Liam is always looking for ways to elevate his customers' coffee experiences.",
    reasons: [
      "Liam is seeking to upgrade his store's equipment to improve efficiency.",
      "He values customer feedback and uses it to inform business decisions.",
      "Liam is exploring new marketing strategies to attract more customers.",
    ],
  },
  {
    id: 4,
    name: "Sophia Patel",
    image: "https://randomuser.me/api/portraits/women/74.jpg",
    topic: "Coffee Bean Supply",
    status: "In Progress",
    created_on: "3/18/2024-12:00 PM",
    title: "Procurement Manager • The Coffee Warehouse",
    note: "Sample shipment • Arriving tomorrow",
    schedule: "Follow up with Sophia on sample shipment",
    schedule_note: "Confirm receipt of sample shipment and discuss next steps",
    about:
      "Sophia Patel, Procurement Manager at The Coffee Warehouse, is an expert in sourcing the finest coffee beans. With her extensive network of suppliers and deep knowledge of the coffee industry, Sophia ensures that The Coffee Warehouse's coffee offerings are always of the highest quality.",
    reasons: [
      "Sophia has established relationships with reliable coffee bean suppliers.",
      "She negotiates contracts to secure the best prices for clients.",
      "Sophia collaborates with the quality control team to ensure products meet standards.",
    ],
  },
  {
    id: 5,
    name: "Ethan Kim",
    image: "https://randomuser.me/api/portraits/men/34.jpg",
    topic: "Equipment Upgrade",
    status: "New",
    created_on: "3/20/2024-01:30 PM",
    title: "Operations Manager • The Coffee Roaster",
    note: "Initial consultation • Next week",
    schedule: "Meet with Ethan to discuss equipment upgrade",
    schedule_note: "Discuss options for upgrading existing equipment",
    about:
      "Ethan Kim, Operations Manager at The Coffee Roaster, is responsible for overseeing the roasting process. With his expertise in coffee roasting and quality control, Ethan ensures that every batch of coffee meets The Coffee Roaster's high standards.",
    reasons: [
      "Ethan is responsible for maintaining the coffee roasting equipment.",
      "He implements efficient production processes to meet demand.",
      "Ethan collaborates with the quality control team to ensure products meet standards.",
    ],
  },
  {
    id: 6,
    name: "Maya Ramos",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    topic: "Marketing Strategy",
    status: "In Progress",
    created_on: "3/22/2024-02:45 PM",
    title: "Marketing Manager • The Coffee Spot",
    note: "Campaign launch • Next month",
    schedule: "Follow up with Maya on marketing campaign",
    schedule_note: "Review campaign progress and discuss next steps",
    about:
      "Maya Ramos, Marketing Manager at The Coffee Spot, is a creative force behind the company's successful marketing campaigns. With her finger on the pulse of the latest coffee trends, Maya develops innovative marketing strategies that drive customer engagement and loyalty.",
    reasons: [
      "Maya has launched successful social media campaigns to engage customers.",
      "She collaborates with the design team to create visually appealing marketing materials.",
      "Maya analyzes customer data to inform marketing strategies.",
    ],
  },
  {
    id: 7,
    name: "Logan Brooks",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
    topic: "Store Design",
    status: "New",
    created_on: "3/25/2024-03:15 PM",
    title: "Store Designer • The Coffee House",
    note: "Initial consultation • Today",
    schedule: "Meet with Logan to discuss store design",
    schedule_note: "Discuss design concepts for new store location",
    about:
      "Logan Brooks is the Store Designer at The Coffee House. With a passion for design, Logan creates inviting store layouts that enhance the customer experience. His expertise in store design enables The Coffee House to establish a strong brand presence and attract loyal customers.",
    reasons: [
      "Logan is responsible for designing store layouts to maximize space.",
      "He selects furniture and decor that align with the brand's aesthetic.",
      "Logan collaborates with the construction team to ensure designs are implemented correctly.",
    ],
  },
  {
    id: 8,
    name: "Ava Morales",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    topic: "Employee Training",
    status: "In Progress",
    created_on: "3/27/2024-04:00 PM",
    title: "Training Manager • The Coffee Academy",
    note: "Training session • Next week",
    schedule: "Follow up with Ava on training session",
    schedule_note: "Confirm training details and discuss next steps",
    about:
      "Ava Morales, Training Manager at The Coffee Academy, is dedicated to educating and inspiring the next generation of coffee professionals. With her extensive experience in coffee training and education, Ava develops comprehensive training programs that equip students with the skills and knowledge needed to succeed in the coffee industry.",
    reasons: [
      "Ava creates customized training programs to address specific needs.",
      "She conducts workshops and one-on-one training sessions.",
      "Ava evaluates training effectiveness to inform future programs.",
    ],
  },
  {
    id: 9,
    name: "Julian Lee",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
    topic: "Supply Chain Management",
    status: "New",
    created_on: "3/29/2024-05:15 PM",
    title: "Supply Chain Manager • The Coffee Warehouse",
    note: "Initial consultation • Next week",
    schedule: "Meet with Julian to discuss supply chain management",
    schedule_note: "Discuss strategies for improving supply chain efficiency",
    about:
      "Julian Lee, Supply Chain Manager at The Coffee Warehouse, is an expert in streamlining logistics and optimizing supply chain operations. With his deep understanding of the coffee supply chain, Julian ensures that The Coffee Warehouse's coffee beans are sourced and delivered efficiently and sustainably.",
    reasons: [
      "Julian negotiates contracts with suppliers to secure competitive prices.",
      "He implements inventory management systems to optimize storage and distribution.",
      "Julian evaluates training effectiveness to inform future programs.",
    ],
  },
  {
    id: 10,
    name: "Gabriella Hall",
    image: "https://randomuser.me/api/portraits/women/35.jpg",
    topic: "Customer Service",
    status: "In Progress",
    created_on: "3/31/2024-06:30 PM",
    title: "Customer Service Manager • The Coffee Club",
    note: "Follow-up call • Tomorrow",
    schedule: "Call Gabriella to discuss customer feedback",
    schedule_note:
      "Review customer feedback and discuss strategies for improvement",
    about:
      "Gabriella Hall, Customer Service Manager at The Coffee Club, is committed to delivering exceptional customer experiences. With her warm and friendly demeanor, Gabriella provides personalized support to customers, ensuring that every interaction with The Coffee Club is positive and memorable.",
    reasons: [
      "Gabriella is responsible for managing The Coffee Club's customer service and has reported a need for improved customer satisfaction",
      "The Coffee Club is looking to increase customer loyalty and retention",
      "Gabriella has researched different customer service strategies and is seeking recommendations",
    ],
  },
  {
    id: 11,
    name: "Caleb Martin",
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    topic: "Equipment Maintenance",
    status: "New",
    created_on: "4/1/2024-09:00 AM",
    title: "Maintenance Manager • The Coffee Roaster",
    note: "Initial consultation • This week",
    schedule: "Meet with Caleb to discuss equipment maintenance",
    schedule_note:
      "Discuss maintenance schedules and procedures for coffee equipment",
    about:
      "Caleb Martin, Maintenance Manager at The Coffee Roaster, is responsible for ensuring the smooth operation of the company's equipment. With his expertise in maintenance and repairs, Caleb keeps The Coffee Roaster's equipment running efficiently, minimizing downtime and maximizing productivity.",
    reasons: [
      "Caleb has implemented a preventive maintenance program that has reduced equipment downtime by 30%",
      "The Coffee Roaster's equipment is now running at optimal levels, thanks to Caleb's expertise",
      "Caleb is exploring new technologies to enhance equipment monitoring and predictive maintenance",
    ],
  },
];

export const demoKeyActivitiesContent = [
  {
    id: 0,
    title: "Cafe A100 for Woodland Bank",
    note: "Woodland Bank • $280,000 • 8 days to close",
    schedule: "Review draft and reply to Chris Naido",
    key: "message",
    logo: "https://logo.uplead.com/amazon.com",
  },

  {
    id: 1,
    title: "Partnership opportunity for Fabrikam",
    note: "Fabrikam • $5,000,000 • 12 days to close",
    schedule: "Prepare me for Fabrikam's key stakeholder meeting",
    key: "schedule",
    logo: "https://logo.uplead.com/airtable.com",
  },
];
