import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { Navbar, Sidebar } from "@/components";

const roboto = Noto_Sans({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  // display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <div className="relative">
          <div className="flex h-screen">
            {/* <div className="bg-primary fixed z-20 flex h-[80px] w-full shadow-xl">
              <Navbar />
            </div> */}

            <Sidebar />
            <div className="w-3/4 flex-grow animate-slide_up overflow-y-auto bg-[#F8F8F8] p-4 pl-12 pt-7">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
